"""
Tests for the Windows update batch generated by the in-app updater.

Regression cover for a bug that shipped silently: the generated `_update.bat`
contained, inside an `if (...)` block,

    echo This install is standalone (no .git folder).

The closing parenthesis terminated the block, leaving a stray `.` behind, and
cmd answered ". was unexpected at this time". Because cmd parses a parenthesised
block *before* executing it, the batch died on **every** install — including
healthy git ones where that branch is never taken. In production the console
flashed and closed, nothing reached the Python side, and the app was left on a
frozen window.

The two rules asserted here:

1. **Parentheses inside an `if (...)` block must be escaped** as `^(` / `^)`.
2. **The batch must be pure ASCII**: it is written as UTF-8 but cmd reads it
   under the OEM codepage.

The template is read from the source rather than duplicated, so the test guards
the artefact actually shipped. If the generation moves, the extraction fails
loudly instead of silently testing nothing.
"""
import re
from pathlib import Path

import pytest

MAIN_WINDOW = (Path(__file__).resolve().parents[1]
               / "src" / "dataforge_studio" / "ui" / "core" / "main_window.py")


def render_batch(project_root: str, relaunch: bool) -> str:
    """Render the batch exactly as `_run_update_on_quit` does."""
    source = MAIN_WINDOW.read_text(encoding="utf-8")
    match = re.search(r"bat_content = f'''(.*?)'''", source, re.S)
    assert match, (
        "Could not find the `bat_content = f'''...'''` template in "
        f"{MAIN_WINDOW.name}. If the batch generation moved, point this test at "
        "its new home — do not delete it."
    )

    root = Path(project_root)
    pythonw = root / ".venv" / "Scripts" / "pythonw.exe"
    run_script = root / "run.py"
    if relaunch:
        end_success = (
            "echo.\n"
            "echo Update complete! Relaunching DataForge Studio...\n"
            f'start "" "{pythonw}" "{run_script}"\n'
            '(del "%~f0") & exit /b 0'
        )
    else:
        end_success = (
            "echo.\n"
            "echo Update complete! Press any key to close.\n"
            "pause\n"
            '(del "%~f0") & exit /b 0'
        )
    return eval(  # noqa: S307 - the template is our own source, not user input
        "f'''" + match.group(1) + "'''",
        {"project_root": root, "end_success": end_success, "chr": chr},
    )


def unescaped_parens_inside_blocks(batch: str):
    """Lines inside an `if (...)` block carrying a block-breaking parenthesis.

    Inside a block, cmd reads a parenthesis appearing in a command's *arguments*
    — `echo something (like this)` — as the end of the block. A line that opens
    with `(` is a nested command group and is parsed correctly, which is why
    `(del "%~f0") & exit /b 1` is legal there while the `echo` line was not.

    So: flag any unescaped parenthesis on a line that does not itself start a
    command group.
    """
    offenders = []
    depth = 0
    for number, line in enumerate(batch.split("\n"), start=1):
        stripped = line.strip()
        opens_block = bool(re.match(r"^(if|for)\b.*\($", stripped))
        closes_block = stripped in (")", ") else (")
        is_command_group = stripped.startswith("(")

        if depth > 0 and not closes_block and not is_command_group:
            bare = re.sub(r"\^[()]", "", stripped)   # drop escaped ones
            if "(" in bare or ")" in bare:
                offenders.append((number, stripped))

        if opens_block:
            depth += 1
        elif closes_block and depth:
            depth -= 1
    return offenders


@pytest.mark.parametrize("relaunch", [True, False])
@pytest.mark.parametrize("project_root", [
    r"C:\DataForge",
    r"C:\Program Files\Data Forge Studio",   # a space in the install path
])
def test_no_unescaped_parenthesis_inside_a_block(project_root, relaunch):
    batch = render_batch(project_root, relaunch)
    offenders = unescaped_parens_inside_blocks(batch)
    assert not offenders, (
        "Unescaped parenthesis inside an `if (...)` block — cmd will close the "
        "block early and the batch dies on every install:\n"
        + "\n".join(f"  line {n}: {line}" for n, line in offenders)
        + "\nEscape them as ^( and ^)."
    )


@pytest.mark.parametrize("relaunch", [True, False])
def test_batch_is_pure_ascii(relaunch):
    batch = render_batch(r"C:\DataForge", relaunch)
    offenders = [
        (number, line.strip())
        for number, line in enumerate(batch.split("\n"), start=1)
        if any(ord(char) > 127 for char in line)
    ]
    assert not offenders, (
        "Non-ASCII character in the batch — it is written as UTF-8 but cmd reads "
        "it under the OEM codepage:\n"
        + "\n".join(f"  line {n}: {line}" for n, line in offenders)
    )


def test_the_detector_catches_the_bug_it_was_written_for():
    """Guard the guard: the exact line that shipped must be reported."""
    shipped = (
        'if not exist ".git" (\n'
        "    echo.\n"
        "    echo This install is standalone (no .git folder).\n"
        "    pause\n"
        ")\n"
    )
    offenders = unescaped_parens_inside_blocks(shipped)
    assert [n for n, _ in offenders] == [3]

    escaped = shipped.replace("(no .git folder)", "^(no .git folder^)")
    assert not unescaped_parens_inside_blocks(escaped)


def test_the_detector_allows_a_nested_command_group():
    """`(del "%~f0") & exit /b 1` is legal inside a block — verified against a
    real cmd. Flagging it would make the detector useless noise."""
    legal = (
        'if not exist ".git" (\n'
        "    echo nothing to do\n"
        '    (del "%~f0") & exit /b 1\n'
        ")\n"
    )
    assert not unescaped_parens_inside_blocks(legal)


def test_relaunch_variant_starts_the_app_detached():
    """The relaunch flavour must hand over to pythonw, not depend on uv."""
    batch = render_batch(r"C:\DataForge", relaunch=True)
    assert "pythonw.exe" in batch
    assert "Relaunching DataForge Studio" in batch
    assert "Press any key to close" not in batch
